### ISSUE TITLE
Checklist for Text Test Notification Launch

### ISSUE THREAD

**Issue by shua123** [smartchicago/kimball#128]
Target: December 7:

- [x] Instead of "Twilio-Wufoo Connections" this page should be renamed "SMS Campaigns" (email sent to testers will be labeled as "Email Campaigns") (Issue #112)
- [x] Put list of outgoing messages under a Communications section (Issue #127)
- [x] On Production - Check which Wufoo API key is used on production 
- [x] Add Signup preference to wufoo field mapping for person. (Issue #129)
- [x] On Production -  Make sure deploy_job worker is running
- [x] On Production - Set up "Hello" SMS Campaign to handle signups
- [x] On Production - Bulk update all "Unknown" CUTGroup testers to EMAIL as preferred method of contact, but will send the email asking their preference. First in staging, then production. (Issue #107)
- [x] On Production - Update people that verified by text message that were affected by last week's outage.
- [x] On Production - Run script to clean up existing phone numbers

**Comment by shua123** [comment]
To start delayed job:
Make sure delayed_job is there ` rails generate delayed_job`
`RAILS_ENV=production bin/delayed_job start`

**Comment by smarziano** [comment]
All of these items are completed and pushed to production. Closing this issue.
